#!/usr/local/bin/php -f
<?

# This check pulls the version from the website and compares it
# to the installed version.
# Many thanks to Atadilo for fixing the code and simplifying it.

# Created 15 Dec 2017
# Modified 12 May 2020
# Modified 18 Sep 2024


$current_installed_buildtime = trim(file_get_contents("/etc/version.buildtime"));
$current_installed_version = trim(file_get_contents("/etc/version"));
$current_installed_platform = trim(file_get_contents("/etc/platform"));

$additional_info .= "OK:  " .$current_installed_platform. " . " .$current_installed_version. " . " .$current_installed_buildtime."\n";

echo $additional_info;
exit ($exitcode);

?>
